language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: GJq6EyXm3akYjcjUXTrdP38dvRZk76lS2P/XNiGEyVrPXNPqcNUjn3tZDI46HZ+FZgtUAvNZj6Q5Lofc3fF2WuK2I1qvMgcw9XhothixYTDweJEV02IqAh4gPdeFlBh8FYRlG0yA3tQu6KkP5hbFcon5mNYjkr1h4Q8Oz8zVGqzzIhm+cal4nySBbac1yctFyjVsJGfvEE8ICaE6MeJAMsudNOflhfM2n3yY3MSvppKmM7HnJ9NkQC2nhigZRRMGFGkPkE29l4exchLJwV6Y3Ds2ayMYcpBAZK5n6PVWz2N3TtZc6A04sXiZc3pLqMLT+fKnSLTrdQR/QfhY9eXn1A2XTUP3gsnQxLzppAcZkfjdJs15jOVdLa+Rk8ZHPbviOaT5uC71XTaxBmsjXrKhgpVDr38c70KAqwU5krexDJNYLc/hekKBnTqC/HdLpNyX0Mi1ItRSqMpkS5jM3dgKjdvXc+/yQGIdbW+GUcy0Tz9tGPQZHCr7hM0f+VXFoX5Drl8kJssAW0ZN+cs2iGl+IBXx6vNphsF3BHnqFK6EHUGAnhEb0ufMqPtsUDN6SdmL1vF+k2lFgEnTgOK8E1gvXKsN6gyyG7Vqh8qDcbS7VlHTxU3md5oEWpsfy9VRfaZ8iQS1mQFQ3dPAGEtMCsqjL0IwTgtQQ6bN4UY3uXA5Za4=
script: mvn clean verify
